### ISSUE TITLE
box hierarchy

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/DRM#3]
Minor comment on the box hierarchy, should it not be traf/saiz and traf/saio (i.e. both these present at traf level)?

**Comment by andrejp** [comment]
Should both be traf/saiz and traf/saio

**Comment by nthorwir** [comment]
yes, thanks. I agree with comment and Andrew: 
It should be 
• moof/traf/saiz                      (one, if encrypted)
• moof/traf/saio                      (one, if encrypted)
not 
• moof/traf/saiz/saiz                         (one, if encrypted)
• moof/traf/saiz/saio                     (one, if encrypted)

**Comment by andrejp** [comment]
Ok need to re-check a diagram and probably fix it. Thank you for pointing out. 

A.

**Comment by ghost** [comment]
Maybe those path errors (‘saiz’/’saiz’) were based on trying to represent sample groups and sample group description ‘seig’ as a path hierarchy at the F2F.
It was confusing because it isn’t a box, so our rough edit might have been misinterpreted later.
Need to check if we are missing something now.

Kilroy Hughes | Senior Digital Media Architect |Windows Azure Media Services | Microsoft Corporation
[cid:image001.png@01CDABBA.71FD8800]http://www.windowsazure.com/media

**Comment by haudiobe** [comment]
There seems to be agreement on the box location. I don’t have any more questions here.

**Comment by haudiobe** [comment]
Agree. Typo will be fixed by Niels
